apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll-api
  template:
    metadata:
      labels:
        app: poll-api
    spec:
      containers:
        - name: poll-api
          image: poll-api-img:latest
          ports:
            - containerPort: 80
