name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ../CriptoBull.sln
    - name: Build API project
      run: dotnet build ../CriptoBull.Api/CriptoBull.Api.csproj --no-restore
    - name: Build Test project
      run: dotnet build ../CriptoBull.Tests/CriptoBull.Tests.csproj --no-restore
    - name: Test
      run: dotnet test ../CriptoBull.Tests/CriptoBull.Tests.csproj --no-build --verbosity normal
